### ISSUE TITLE
getting null for all origin-destination combinations

### ISSUE THREAD

**Issue by malleswar22** [higgicd/Accessibility_Toolbox#3]
I used your tool to calculate accessibility but continuously getting null for SUM_Ai in arcgis_pro.
could anyone tell me why and how to rectify it. 

does it have to do anything with the "travel mode...." I used "car". and cutoff value as 60 minutes.

**Comment by darrennel** [comment]
I don't think it will be the travel mode. The problem is likely due to having 'null values' in the destination opportunities. Can you check and confirm if this is the case?

**Comment by malleswar22** [comment]
Thanks for quick reply.  I checked and didn't have any null values. 

Does it have to do anything with network dataset? Because I download roads Shapefile from open street map and directly converted to to network dataset in arcgis pro. There were no attributes to define direction and other variables while making network dataset. 

So I just define transport mode as car and used it in the accessibility calculator.

![Screenshot (15)](https://user-images.githubusercontent.com/87108425/132313318-f97e43ff-8e0c-4c57-a704-ae47c6c96430.png)


I've attached a screen shot of the result.

all the sum_expo values are <null>

I don't understand why. please help me.

Thank you.

**Comment by higgicd** [comment]
All of your origins are connecting to a single "destination" (this is what Frequency is counting) - no doubt the origin itself, suggesting your network doesn't work correctly...

**Comment by malleswar22** [comment]
Do you have any idea or can you please help me how to correct this? 

How to make this network dataset from open street map to work?

**Comment by darrennel** [comment]
> Do you have any idea or can you please help me how to correct this?
> 
> How to make this network dataset from open street map to work?

You can take a look here on how to create a network: https://pro.arcgis.com/en/pro-app/latest/help/analysis/networks/how-to-create-a-usable-network-dataset.htm

For the accessibility tool, you need to make sure that your impedance unit (your measure of distance/travel cost) is in **minutes** and not distance/length (i.e. meters). So if you are using 'car' as your travel mode, then, when you create your network, you need to set travel cost to be in minutes. If your network setting is in length then you will have issues with the tool. 

Also, did you test that your network was working properly? You can do this by calculating some basic routes/closest facilities between a few different points (see image)
![image](https://user-images.githubusercontent.com/45100570/132441846-bdecd7f1-e38e-479b-944b-a3710f88fd6d.png)

**Comment by malleswar22** [comment]
Thank you so much for your valuable corrections. I reconstructed the network dataset and changed attributes as you said in the above comment(impedance). and it worked!!!! 

Thank you.
