### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by malleswar22** [higgicd/Accessibility_Toolbox#4]
I've 

origins = 4012245 & destination = 22765(hospitals)

Your tool is working and, the result(output) has only 9741 rows with all the frequency data and chosen accessibility values. Could you please make a comment on this like what would have been the reason? 

Because Last time I did this operation with origins = 2500000, The output had accessibility results for all the origins(there were 2500000 rows in the output table). I couldn't understand why this time it changed.

Could you please tell me how to visualize accessibility values in ArcGIS pro using symbology?

Thank you in advance.

**Comment by malleswar22** [comment]
could you please tell me why all the origins FID = 0? I selected the origins with the FID = 0.

Only the 9741 origins are not selected as we can see in the picture( the top part of the map is not selected ). Only these have accessibility values. And the rest of them are not present in the output table.

Please help. I want the accessibility values for the entire data.

![Screenshot (2)](https://user-images.githubusercontent.com/87108425/136144637-20a403f3-1725-4b3e-88f5-6304be72a341.png)
![Screenshot (4)](https://user-images.githubusercontent.com/87108425/136144639-280af99a-d4a7-47d2-8487-305723ac0a79.png)

**Comment by darrennel** [comment]
> could you please tell me why all the origins FID = 0? I selected the origins with the FID = 0.
> 
> Only the 9741 origins are not selected as we can see in the picture( the top part of the map is not selected ). Only these have accessibility values. And the rest of them are not present in the output table.
> 
> Please help. I want the accessibility values for the entire data.
> 
> 

Did the FID field have unique values in the original file? If not, then if you use them as your _origins ID field_ then you will have some issues with the tool. Sometimes it's best to create a new field where you create your own unique ID for each feature. This also means that it's easier to partition and rejoin your data if you need to. 

For example, in the first image I created a new field _NYCPLID_ (highlighted) and gave each feature a unique ID. I then used this field as my _origins ID field_ for the analysis

![image](https://user-images.githubusercontent.com/45100570/136162741-47ed77bf-c9f1-4a1d-b059-b372069a7bd8.png)

In the second image you can see the results of the output table are shown. Again, as highlighted, the the unique ID of the original filed has been carried over. It is then possible to use this field to link the output data back to the original input file that can then be used for further analysis or visualization. 
![image](https://user-images.githubusercontent.com/45100570/136163645-38029091-7903-4237-91e6-ecd877baa091.png)

**Comment by malleswar22** [comment]
I have a unique FID for all the poi. I'll try again with your suggestion, Thank you
