### ISSUE TITLE
Suggestions for handling r5r

### ISSUE THREAD

**Issue by rafapereirabr** [higgicd/Accessibility_Toolbox#5]
Hi Chris,

Thanks for this is a great toolbox. I was browsing the code related to `r5r` and just wanted to flag a couple things that would

### 1. Set Java memory
Ideally, one should set the Java memory before loading any libraries. This is to make sure Java will get the memory you set. In case you load a library that call `.jInit()`, then the call for `options(java.parameters = Xmx...)` could lose effect.
```
options(java.parameters = "-Xmx6G") # assign memory for r5r to work with
library(r5r)
library(...)

```

### 2. Accessibility calculation

I understand one might want to calculate travel time matrices and store the data for future use. Nonetheless, if the purpose is simply to calculate accessbility, then it would be best (simpler and more efficient) to use the `r5r::accessibility()` function.

**Comment by higgicd** [comment]
Fixed issue 1, thanks! And re number two, this was all coded prior to the addition of `r5r::accessibility()`, so I have kept it the same. Looks like you are working on something along these lines as well in https://github.com/ipeaGIT/accessibility :)

**Comment by rafapereirabr** [comment]
Hi Chris. The `r5r::accessibility()` is super fast. It makes it calculating accessibility estimates much easier and much much faster. However, this function is limited to a few metrics. So we've decided to create `accessibility`, a separate R pacakge to help calculating accessibility with other accessibility metrics. This new package is more flexible also, so it can be used with input data generated by other routing engines
